### ISSUE TITLE
New name for POST /improve

### ISSUE THREAD

**Issue by JupiterPi** [ChristianBKraus/midgard2#4]
Hello ChristianBKraus!

I'd like to make a change to the name of the request mapping "/improve". The request is used to get the reward of an adventure the character successfully played. So a good name for it would be "/reward". 

Thank you!
JupiterPi

**Comment by ChristianBKraus** [comment]
Better use grant

**Comment by JupiterPi** [comment]
Okay. I will now close this issue.
